---
name: "TheMovieDbAdult"
guid: "6ce05665-2256-48a4-a2a8-f2bad5e0003c"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "neydor"
overview: "Get metadata for adult content from TheMovieDb"
description: >
  Get metadata for adult content from TheMovieDb
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.TmdbAdult.dll"
- "TMDbLib.dll"
changelog: >
  Remove from Jellyfin core.
